apiVersion: apps/v1
kind: Replicaset
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx 
          image: nginx:1.19.2
          resources:
            limits:
              cpu: 0.5
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 120Mi
 
